name: flutter_animaciones_notificaciones
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.1
  intl: ^0.20.2
  timezone: 0.10.1
  permission_handler: ^11.3.0
  flutter_local_notifications: 19.2.1
  #hive + soporte flutter Practica 24 Junio
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
  # generar el codigo de hive Practica 24 Junio
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

